esphome:
  name: humidifier
  friendly_name: Smartmi Evaporative Humidifier 2

  platformio_options:
    upload_speed: 115200

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true

external_components:
  - source:
      type: local
      path: .
    components: [ miio ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

ota:

api:

logger:

time:
  - platform: homeassistant

uart:
  id: mcu
  baud_rate: 115200
  tx_pin: 17
  rx_pin: 16

miio:

switch:
  - id: power
    platform: miio
    cluster: 2
    key: 1
    name: Power
    icon: mdi:power

  - id: buzzer
    platform: miio
    cluster: 4
    key: 1
    name: Buzzer
    icon: mdi:bell

  - id: touchscreen_lock
    platform: miio
    cluster: 6
    key: 1
    name: Touchscreen lock
    icon: mdi:gesture-tap-button

select:
  - id: operation_mode
    platform: miio
    cluster: 2
    key: 5
    name: Mode
    icon: mdi:fan
    optimistic: true
    options:
      0: Auto
      1: Slow
      2: Medium
      3: Fast

  - id: display_brightness
    platform: miio
    cluster: 5
    key: 2
    name: Display brightness
    icon: mdi:brightness-6
    optimistic: true
    options:
      0: "Off" # i love YAML
      1: Dim
      2: Bright

sensor:
  - id: water_tank_level
    platform: miio
    cluster: 2
    key: 7
    name: Water tank level
    icon: mdi:water # TODO: find better icon?
    unit_of_measurement: "%"
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 127.0 -> 100.0

  - id: temperature
    platform: miio
    cluster: 3
    key: 7
    name: Temperature
    device_class: temperature
    accuracy_decimals: 1
    unit_of_measurement: "°C"

  - id: humidity
    platform: miio
    cluster: 3
    key: 9
    name: Humidity
    device_class: humidity
    unit_of_measurement: "%"

  - id: fan_speed
    platform: miio
    cluster: 2
    key: 11
    name: Fan speed
    device_class: speed
    entity_category: diagnostic
    unit_of_measurement: RPM

  - id: total_operating_time
    platform: miio
    cluster: 2
    key: 9
    name: Total use time
    device_class: duration
    state_class: total_increasing
    entity_category: diagnostic
    unit_of_measurement: s
