esphome:
  name: intercom
  friendly_name: Intercom

esp8266:
  board: d1_mini

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

output:
  - platform: gpio
    id: unlock_relay
    pin: 5

button:
  - platform: output
    id: intercom_unlock
    output: unlock_relay
    name: Unlock
    icon: mdi:doorbell
    duration: 300ms

binary_sensor:
  - platform: gpio
    id: intercom_ring
    pin: 4
    name: Ring
    icon: mdi:bell-ring
    filters:
      - delayed_off: 4.5s

sensor:
  - platform: uptime
    name: Uptime
    state_class: total_increasing
    unit_of_measurement: s
