esphome:
  name: rapid-ir
  friendly_name: Rapid Remote

esp8266:
  board: esp_wroom_02

external_components:
  - source:
      type: local
      path: .
    components: [ rapid ]

logger:
  level: INFO

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

light:
  - platform: status_led
    id: status
    pin: GPIO4

binary_sensor:
  - platform: gpio
    id: service_key
    pin:
      number: GPIO13
      inverted: true

sensor:
  - platform: homeassistant
    id: ambient_temperature
    entity_id: sensor.sprite_temperature

remote_receiver:
  id: ir_receiver
  pin:
    number: GPIO5
    inverted: true

remote_transmitter:
  id: ir_transmitter
  pin: GPIO14
  carrier_duty_percent: 50%

climate:
  - platform: rapid
    name: Rapid
    receiver_id: ir_receiver
    transmitter_id: ir_transmitter
    sensor: ambient_temperature

    visual:
      temperature_step: 1
