esphome:
  name: tv-backlight
  friendly_name: TV Backlight

esp8266:
  board: d1
  
logger:
  level: INFO

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    ssid: 'Fallback AP: TV Backlight'
    password: !secret ap_password

captive_portal:

output:
  - platform: gpio
    id: relay
    pin:
      number: D13
      inverted: true

light:
  - platform: binary
    id: tv_illumination
    name: Illumination
    output: relay
